### ISSUE TITLE
Импорт java библиотек и кода в проектах

### ISSUE THREAD

**Issue by mikhailmineev** [aurusov/raox#601]
Добавить возможность импортировать java библиотеки и чистый java код в проекты

**Comment by AlexChern0v** [comment]
Это разве не работает из коробки?

**Comment by mikhailmineev** [comment]
Компиляция да
Создать модель (test)

Создать ПКМ->New->Source folder (имя src) 
В srс создать класс TestClass

```java
package test;

public class TestClass {
	
	public static String get() {
		return "Text";
	}
}
```

В файле модели создать 

```java
def init() {
	log(TestClass.get())
}
```

Компиляция успешно пройдет

Симуляция нет

```
java.lang.NoClassDefFoundError: test/TestClass
	at test.test$init.run(test.java:11)
	at ru.bmstu.rk9.rao.lib.simulator.Simulator.initialize(Simulator.java:44)
	at ru.bmstu.rk9.rao.lib.simulator.CurrentSimulator.initialize(CurrentSimulator.java:44)
	at ru.bmstu.rk9.rao.ui.execution.ExecutionJobProvider$1.run(ExecutionJobProvider.java:81)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: test.TestClass
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

**Comment by AlexChernov** [comment]
Проверь не сломали ли classloader и вообще убедись что ты в нужном месте создаешь класс. Это точно работало раньше. По крайней мере я создавал кастомный обработчик статистики на Java и это работало. Cм. [Лист Результаты](http://aurusov.github.io/diploma/2016/%D0%9F%D0%BE%D0%B4%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0%20%D1%81%D0%BE%D0%B1%D0%B8%D1%80%D0%B0%D0%B5%D0%BC%D1%8B%D1%85%20%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9%20%D0%B2%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5%20%D0%B8%D0%BC%D0%B8%D1%82%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20Rao%20X%20-%20%D0%A7%D0%B5%D1%80%D0%BD%D0%BE%D0%B2%20%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9%20-%20%D0%A0%D0%9A9-28%D0%9C/%D0%9B%D0%B8%D1%81%D1%82%D1%8B.pdf)

**Comment by mikhailmineev** [comment]
Разобрал случай, что ты показал.

```java
result всего_обслужено = Result.create([парикмахерская.количество_обслуженных], new TestClass())
```
В такой ситуации TestClass инициализируются благодаря результатам, и к нему можно уже везде ссылаться.

Но нужна возможность нормальной инициализации, не подсовывая классы в те места, где их проинициализируют.

**Comment by mikhailmineev** [comment]
Что интересно, данная реализация переваривает мавен проект, что позволяет не испытывать большую боль при добавлении библиотек

**Comment by mikhailmineev** [comment]
Пример https://github.com/mikhailmineev/raox_jpa_model
